### PR TITLE
reafac: useless code cleanup

### LINKED ISSUE #88: Refac: Delete all instances of burn rate
`Burn Rate` feature is no longer needed, and it's logic seems to be also wrong.

### PR DESCRIPTION
**Pull request by Supremesource**
Values of:
- Burn rate
- Min Stake
Don't add any meaningful value to the blockchain, except just introducing complexity.
Deleted dead code, or moved to tests/mock
Closes #88

### CODE REVIEW

File: node/src/chain_spec.rs
Comment (saiintbrisson) [inline node/src/chain_spec.rs:1]: You'd have to also change the spec files

Comment (Supremesource) [reply node/src/chain_spec.rs:1]: I can do it tomorrow

File: CHANGELOG [hunk 1]
```diff
@@ -1,5 +1,11 @@
 # Changelog
 
+[Unreleased]
+
+- Deleted, or moved useless code and values of:
+- Burn rate
+- Min Stake
```
Comment (saiintbrisson) [inline CHANGELOG:7]:
```suggestion
- Deleted, or moved useless code and values of:
  - Burn rate
  - Min Stake
```
