### PR TITLE
refac(pallets/subpsace): use dispatch results

### LINKED ISSUE #137: Improving Anti Panic Safety
> Work is being done on the `main` branch

We still use the `#![allow(clippy::arithmetic_side_effects, clippy::indexing_slicing)]` that should not be the case in any part of the blockchain. The code should have absolutely no way to panic, even in extrinsics, if there would be a way to panic in extrinsic,  return an error.

- What is an extrinsic ? 
Extrinsics are functions located under the pallet call, see
https://github.com/agicommies/subspace-network/blob/main/pallets/subspace/src/lib.rs#L755

Example of potential extrinsic panic
https://github.com/agicommies/subspace-network/blob/main/pallets/subspace/src/set_weights.rs#L13
Here at the place of potential panic, if panic were to happen, you will return an error
```rs
   Error::<T>::ExtrinsicPanicked
```
Or similar, depending on the situation (more descriptive errors prefered)

Another large part of possible panics is in the subspace/math file, where we ignore all of them.

### PR DESCRIPTION
**Pull request by aripiprazole**
Closes #137

### CODE REVIEW

File: pallets/subspace/src/step.rs [hunk 1]
```diff
@@ -434,25 +442,32 @@ impl<T: Config> Pallet<T> {
...
+    ) -> Result<(Vec<u16>, Vec<I32F32>), sp_runtime::DispatchError> {
         let n = incentive.len();
         let mut dividends: Vec<I32F32> = vec![I32F32::from_num(0.0); n];
 
         for (i, sparse_row) in bonds.iter().enumerate() {
             for (j, value) in sparse_row.iter() {
-                dividends[i] += incentive[*j as usize] * *value;
+                let incentive_i = match incentive.get(*j as usize) {
+                    Some(value) => *value,
+                    None => Err(Error::<T>::ExtrinsicPanicked)?,
```
Comment (Supremesource) [inline pallets/subspace/src/step.rs:457]:
```suggestion
                    None => Err(Error::<T>::StepPanicked)?,
```

File: pallets/subspace/src/step.rs [hunk 2]
```diff
@@ -461,38 +476,41 @@ impl<T: Config> Pallet<T> {
...
         let mut bonds: Vec<Vec<(u16, I32F32)>> = weights.to_vec();
         let mut col_sum: Vec<I32F32> = vec![I32F32::from_num(0.0); n];
 
         for (i, sparse_row) in bonds.iter_mut().enumerate() {
             for (j, value) in sparse_row.iter_mut() {
-                *value *= stake[i];
-                col_sum[*j as usize] += *value;
+                *value = match stake.get(i) {
+                    Some(v) => value.saturating_mul(*v),
+                    None => Err(Error::<T>::ExtrinsicPanicked)?,
```
Comment (Supremesource) [inline pallets/subspace/src/step.rs:495]:
```suggestion
                    None => Err(Error::<T>::StepPanicked)?,
```

**Review by Supremesource — CHANGES_REQUESTED** [review]

File: pallets/subspace/src/math.rs [hunk 3]
```diff
@@ -62,7 +66,13 @@ pub fn matmul_sparse(
             // Compute ranks: r_j = SUM(i) w_ij * s_i
             // Compute trust scores: t_j = SUM(i) w_ij * s_i
             // result_j = SUM(i) vector_i * matrix_ij
-            result[*j as usize] += vector[i] * value;
+            let Some(target) = result.get_mut(*j as usize) else {
+                continue;
```
Comment (devwckd) [inline pallets/subspace/src/math.rs:70]: Shouldn't this return a result instead of continuing if the vectors aren't the expected size? There's a small chance of it happening but if it does, we'd never know, and the chain would operate on wrong numbers. (Counts for the other similar cases as well)

**Comment by Supremesource** [comment]
Move the 
```toml
[lints.clippy]
arithmetic_side_effects = "deny"
indexing_slicing = "deny"
panicking_unwrap = "deny"
out_of_bounds_indexing = "deny"
```
To the root of the `Cargo.toml`

**Review by Supremesource — CHANGES_REQUESTED** [review]
Move the 
```toml
[lints.clippy]
arithmetic_side_effects = "deny"
indexing_slicing = "deny"
panicking_unwrap = "deny"
out_of_bounds_indexing = "deny"
```
To the root of the `Cargo.toml`

**Review by Supremesource — APPROVED** [review]
LGTM

**Comment by saiintbrisson** [comment]
@aripiprazole as with the ongoing development on `feat/global-stake-v2`, this will be a massive headache if we merge it now. You have two options: rebasing this on top of `feat/global-stake-v2` and merge it to that branch, or waiting until we merge it main first. Which one do you wanna go with?

**Comment by aripiprazole** [comment]
> @aripiprazole as with the ongoing development on `feat/global-stake-v2`, this will be a massive headache if we merge it now. You have two options: rebasing this on top of `feat/global-stake-v2` and merge it to that branch, or waiting until we merge it main first. Which one do you wanna go with?

I can rebase on top of `feat/global-stake-v2` tomorrow. I think it will be done more quickly if I do this.

**Comment by Supremesource** [comment]
> > @aripiprazole as with the ongoing development on `feat/global-stake-v2`, this will be a massive headache if we merge it now. You have two options: rebasing this on top of `feat/global-stake-v2` and merge it to that branch, or waiting until we merge it main first. Which one do you wanna go with?
> 
> I can rebase on top of `feat/global-stake-v2` tomorrow. I think it will be done more quickly if I do this.

Yes ! Please rebase it there, at least we will have it in the tests already
